import { Component, OnInit } from '@angular/core';
import { EdgarPreviewService } from 'src/app/services/edgar-preview.service';
import { EdgarSearchService } from 'src/app/services/edgar-search.service';
import { TickerSyncService } from 'src/app/services/ticker-sync.service';
import { FillingsStucture } from 'src/app/interfaces/fillings-structure';

@Component({
  selector: 'app-fillings',
  templateUrl: './fillings.component.html',
  styleUrls: ['./fillings.component.scss']
})
export class FillingsComponent implements OnInit {

  company!: string;
  links: string[] = [];
  filingsData: FillingsStucture = {
    addresses: {
      business: {
        city: '',
        stateOrCountry: '',
        stateOrCountryDescription: '',
        street1: '',
        street2: '',
        zipCode: ''
    },
    mailing: {
        city: '',
        stateOrCountry: '',
        stateOrCountryDescription: '',
        street1: '',
        street2: '',
        zipCode: ''
    }
    },
    category: '',
    cik: '',
    description: '',
    ein: '',
    entityType: '',
    exchanges: [],
    filings: {
      files: [],
      recent: {
          acceptanceDateTime: [],
          accessionNumber: [],
          act: [],
          fileNumber: [],
          filingDate: [],
          filmNumber: [],
          form: [],
          isInlineXBRL: [],
          isXBRL: [],
          items: [],
          primaryDocDescription: [],
          primaryDocument: [],
          reportDate: [],
          size: []
      }
    },
    fiscalYearEnd: '',
    flags: '',
    formerNames: [],
    insiderTransactionForIssuerExists: 0,
    insiderTransactionForOwnerExists: 0,
    investorWebsite: '',
    name: '',
    phone: '',
    sic: '',
    sicDescription: '',
    stateOfIncorporation: '',
    stateOfIncorporationDescription: '',
    tickers: [],
    website: ''
  };
  filingsArray: any = [];
  submissionForms = {
    '10-12B': 'a|3|Registration of securities [Section 12(b)]',
    '10-12G': 'a|3|Registration of securities [Section 12(g)]',
    '10-C': 'a| |Change of number of shares outstanding or change of issuer name',
    '10-D': 'a| |Asset-Backed Issuer Distribution Report [Section 13 or 15(d) of the Securities Exchange Act of 1934]',
    '10-K405': 'a|3|Annual report [Sections 13 and 15(d), S-K Item 405]',
    '10-K': 'a|3|Annual report [Section 13 and 15(d), not S-K Item 405]',
    '10KSB405': 'a|3|Optional form for annual and transition reports of small business issuers [Section 13 or 15(d), S-B Item 405]',
    '10KSB40': 'a| |Annual Report Form for Small Businesses that also have a Positive Response to Item 405',
    '10KSB': 'a|3|Optional form for annual and transition reports of small business issuers [Section 13 or 15(d), not S-B Item 405]',
    '10KT405': 'a| |Transition reports pursuant to Rule 13a-10 or 15d-10, Initial Filing',
    '10-KT': 'a|3|Transition reports [Rule 13a-10 or 15d-10]',
    '10-M': ' | |Irrevocable appointment of agent by individual nonresident broker or dealer',
    '10-Q': 'a|3|Quarterly report [Sections 13 or 15(d)]',
    '10QSB': 'a|3|Optional form for quarterly and transition reports of small business issuers',
    '10-QT': 'a|3|Transition reports [Rule 13a-10 or 15d-10]',
    '10SB12B': 'a|3|Registration of securities for small business [Section 12(b)]',
    '10SB12G': 'a|3|Registration of securities for small business [Section 12(g)]',
    '11-K': 'a|3|Annual report of employee stock purchase, savings and similar plans',
    '11-KT': 'a|3|Transition report [Rule 13a-10 or 15d-10]',
    '12G-2': ' | |Securities deemed to be Registered [Section 12(g)(1)]',
    '12G3-2A': ' | |Exemptions for American Depository Receipts and Certain Foreign Securities',
    '12G3-2B': ' | |Exemptions for American Depository Receipts and Certain Foreign Securities',
    '12G32BR': ' | |Exemptions for American Depository Receipts and Certain Foreign Securities',
    '13FCONP': 'a| |Quarterly report filed by institutional managers, Holdings',
    '13F-E': 'a| |Quarterly reports filed by institutional managers.',
    '13F-HR': 'a|3|Quarterly report filed by institutional managers, Holdings',
    '13F-NT': 'a|3|Quarterly report filed by institutional managers, Notice',
    '144': 'a|2|Report of proposed sale of securities',
    '15-12B': 'a|3|Securities registration termination [Section 12(b)]',
    '15-12G': 'a|3|Securities registration termination [Section 12(g)]',
    '15-15D': 'a|3|Suspension of duty to report [Section 13 and 15(d)]',
    '15F-12B': 'a||Securities registration termination of foreign private issuers [Section 12(b)]',
    '15F-12G': 'a||Securities registration termination of foreign private issuers [Section 12(g)]',
    '15F-15D': 'a||Suspension of duty to report for foreign private issuers [Section 13 and 15(d)]',
    '18-12B': 'a|3|Registration of securities [Section 12(b)]',
    '18-12G': 'a|3|Registration of securities [Section 12(g)]',
    '18-K': 'a|3|Annual report for foreign governments and political subdivisions',
    '19B-4': 'a| |Proposed Rule Change by SRO [Rule 19b4]',
    '19B-4E': ' | |Information required of an SRO Listing and Trading a New Directive Securities Product [Rule 19b-4(e)]',
    '19-B': 'a| |For Filings with Respect to Proposed Rule Changes by All Self-Regulatory Organizations',
    '1-A': 'a| |Offering Statement [Regulation A]',
    '1': 'a| |Application for Registration or Exemption from Registration as a National Securities Exchange',
    '1-A-W': 'a| |Withdrawal of offering statement [Regulation A]',
    '1-E': ' | |Notification [Regulation E]',
    '20-F': 'a|3|Annual and transition report of foreign private issuers [Sections 13 or 15(d)]',
    '20FR12B': 'a|3|Registration of securities [Section 12(b)]',
    '20FR12G': 'a|3|Registration of securities [Section 12(g)]',
    '20-FR': ' | |Annual and transition registration statement of foreign private issuers [Sections 13 or 15(d)]',
    '24F-1': ' | |Registration of securities by certain investment companies [Rule 24F-1]. Notification of election.',
    '24F-2EL': 'a| |Registration of securities by certain investment companies [Rule 24F-2]. Declaration of election.',
    '24F-2NT': 'a|1|Rule 24F-2 notice',
    '24F-2TM': 'a| |Registration of securities by certain investment companies [Rule 24F-2]. Termination of Declaration of election.',
    '25': 'a| |Notification of the removal from listing and registration of matured, redeemed or retired securities',
    '25-NSE': ' | |Notification filed by national security exchange to report the removal from listing and registration of matured, redeemed or retired securities',
    '26': 'a| |Notification of the admission to Trading of a Substituted or additional class of security',
    '27': 'a| |Notification of changes in securities admitted to unlisted trading privileges',
    '28': 'a| |Notification of the termination or suspension of unlisted trading privileges.',
    '2-A': 'a| |Report of Sales [Regulation A]',
    '2-AF': ' | |Final Report of Sales of Securities [Rule 260]',
    '2-E': 'a| |Reports of sales of securities [Regulation E]. Filed by investment companies.',
    '305B2': 'a|3|Filing [Trust Indenture Act]',
    '34-12H': ' | |Application for Exemption [Section 12(g)] or from filing certain reports [Section 13(a)]',
    '34-36CF': ' | |Application for exemption relief [Section 36 Corporation Finance]',
    '34-36MR': ' | |Application for exemption relief [Section 36 Market Regulations]',
    '35-11': 'a| |Certain Acquisitions by Affiliates exempted from Section 9(a)(2)',
    '35-2': ' | |Application for exemption for holding companies which are Intrastate or predominately operating companies',
    '35-3': ' | |Application for exemption for certain banks',
    '35-7B': ' | |Application for exemption [Rule 7(b)(1)]',
    '35-APP': 'a|3|Statement on proposed transaction where no application is prescribed [Rule 20(e)]',
    '35-CERT': 'a|3|Certificate, terms and conditions [Rule 24]',
    '39-10B2': ' | |Application [Rule 10B-2]',
    '39-304C': ' | |Application for exemption from certain provisions of the Trust Indenture Act of 1939',
    '39-304D': ' | |Application to exempt any person, registration statement, indenture security or transaction or any class or classes of persons, registration statements, indentures, securities or transactions from one or more provisions of the Act',
    '39-310B': ' | |Application regarding conflict of interest under the Trust Indenture Act of 1939',
    '3': 'a|2|Initial statement of beneficial ownership of securities',
    '40-17F1': 'a|2|Certificate of accounting of securities in custody of management investment companies [Rule 17f-1]',
    '40-17F2': 'a|2|Certificate of accounting of securities in custody of management investment companies [Rule 17f-2]',
    '40-17G': 'a| |Fidelity Bond [Rule 17G-1(g)]',
    '40-202A': 'a| |Application to designate applicant a person not within the intent of the Investment Advisers Act of 1940',
    '40-203A': ' | |Exemption from the Prohibition on Commission Registration',
    '40-205A': ' | |Performance Fees exemption that would permit Investment Advisors to charge performance fees to certain types of clients or for certain transactions',
    '40-205E': 'a| |Application for performance fees exemption [Section 205]',
    '40-206A': ' | |Application for exemption [Section 206(3)]',
    '40-24B2': ' | |Filing of sales literature pursuant to Rule 24b2 under the Investment Company Act of 1940',
    '40-33': 'a| |Copies of all Stockholder Derivative Actions filed with a court against an Investment Company or an Affiliate thereof [Section 33]',
    '40-6B': ' | |Application for exemption from all provisions of The Investment Company Act of 1940 by an Employee\'s Investment Company',
    '40-6C': 'a| |Application for exemption and other relief [Section 6(c)]',
    '40-8B25': ' |2|Investment company request for extension of time to file',
    '40-8F-2': 'a|2|Application for deregistration [Rule O-2]',
    '40-8F-A': 'a|2|Application for deregistration, abandonment of registration',
    '40-8F-B': 'a|2|Application for deregistration, business development company',
    '40-8FC': 'a| |Investment Company Registration withdrawn by Commission Order',
    '40-8F-L': 'a|2|Application for deregistration, liquidation',
    '40-8F-M': 'a|2|Application for deregistration, merger',
    '40-APP': 'a| |Application for exemption and other relief filed under the Investment Company Act of 1940',
    '40-F': 'a| |Annual report - foreign issuer [Section 13(a), 15(d)]',
    '40FR12B': 'a| |Registration of a Class of Securities of certain Canadian issuers [Section 12(b)]',
    '40FR12G': ' | |Registration of a Class of Securities of certain Canadian issuers [Section 12(g)]',
    '40-OIP': ' | |Applications under the Investment Company Act reviewed by Office of Insurance Products',
    '40-RPT': 'a| |Reports required to be filed by certain applicants for exemptions from the Investment Company Act of 1940',
    '424A': ' |3|Prospectus [Rule 424(a)]',
    '424B1': ' |3|Prospectus [Rule 424(b)(1)]',
    '424B2': ' |3|Prospectus [Rule 424(b)(2)]',
    '424B3': ' |3|Prospectus [Rule 424(b)(3)]',
    '424B4': ' |3|Prospectus [Rule 424(b)(4)]',
    '424B5': ' |3|Prospectus [Rule 424(b)(5)]',
    '424B7': ' |3|Prospectus [Rule 424(b)(7)]',
    '424B8': 'a| |Prospectus filed pursuant to Rule 424(b)(8)',
    '425': ' |2|Prospectuses and communications, business combinations',
    '45B-3': 'a|2|Transitional statement, extensions of credit [Rule 45(b)(3)]',
    '485A24E': ' | |Post Effective Amendments',
    '485A24F': ' | |Post Effective Amendments',
    '485APOS': ' |3|Post-effective amendment [Rule 485(a)]',
    '485B24E': ' | |Post Effective Amendments',
    '485B24F': ' | |Post Effective Amendments',
    '485BPOS': ' |3|Post-effective amendment [Rule 485(b)]',
    '485BXT': ' |3|New effective date for post-effective amendment [Rule 485(b)(1)(iii)]',
    '485BXTF': ' | |Post Effective Amendments to designate new effective dates',
    '486A24E': ' | |Post Effective Amendments of N-2s',
    '486APOS': ' |3|Post-effective amendment [Rule 485(a)]',
    '486B24E': ' | |Post Effective Amendments of N-2s',
    '486BPOS': ' |3|Post-effective amendment [Rule 485(b)]',
    '487': ' |1|Pre-effective pricing amendments [Rule 487]',
    '497': ' |3|Definitive materials',
    '497AD': ' |3|Filing by certain investment companies of Rule 482 advertising [Rule 497 and 482(c)]',
    '497H2': ' |3|Filings [Rule 497(h)(2)]',
    '497J': ' |3|Certification of no change in definitive materials',
    '497K1': ' |3|Profiles for certain open-end management investment companies, [Rule 497(k)(1)(i)]',
    '497K2': ' |3|Profiles for certain open-end management investment companies, [Rule 497(k)(1)(ii)]',
    '497K3A': ' |3|Profiles for certain open-end management investment companies, [Rule 497(k)(1)(iii)(A)]',
    '497K3B': ' |3|Profiles for certain open-end management investment companies, [Rule 497(k)(1)(iii)(B)]',
    '497K': 'a||Summary Prospectus for certain open-end management investment companies filed pursuant to Securities Act Rule 497(K)',
    '4': 'a|2|Statement of changes in beneficial ownership of securities',
    '5': 'a|2|Annual statement of changes in beneficial ownership of securities',
    '6B NTC': ' | |40-6B Notice',
    '6B ORDR': ' | |40-6B Order',
    '6-K': 'a|3|Report of foreign issuer [Rules 13a-16 and 15d-16]',
    '7-A': 'a| |Optional Form of Escrow for Securities [Rule 253(c) of Regulation A]',
    '8-A12B': 'a|3|Registration of securities [Section 12(b)]',
    '8A12BEF': ' | |Registrations of certain classes of Securities',
    '8A12BT': 'a| |Registrations of certain classes of Securities',
    '8-A12G': 'a|3|Registration of securities [Section 12(g)]',
    '8-B12B': 'a| |Registrations of Securities of certain successor issuers',
    '8-B12G': 'a| |Registrations of Securities of certain successor issuers',
    '8F-2 NTC': ' | |40-8F-2 Notice',
    '8F-2 ORDR': ' | |40-8F-2 Order',
    '8-K12B': ' | |Notification that a class of securities of successor issuer is deemed to be registered pursuant to section 12(b)',
    '8-K12G3': 'a|3|Notification of securities of successor issuers deemed to registered [Section 12]',
    '8-K15D5': 'a|3|Notification of assumption of duty to report by successor issue [Section 15(d)]',
    '8-K': 'a|3|Current report',
    '8-M': ' | |Consent to service of process by Notice, Corporation non-Resident BD',
    '9-M': ' | |Consent to service of process by Notice, Partnership non-Resident BD',
    'ABS-15G': 'a||Asset-backed securitizer report pursuant to Section 15G',
    'ABS-EE': 'a||Asset-Backed Electronic Exhibits',
    'ADB': 'a| |Periodic reports filed by the Asian Development Bank',
    'ADN-MTL': ' | |Additional or Detached Materials for which no Rule or Regulation applies or No Specific Form is Prescribed',
    'ADV': 'a| |Registration of Investment Advisor',
    'ADVCO': ' | |Cancellation of registered advisers by commission order',
    'ADV-E': ' | |Certificate of Accounting of Client Securities and Funds in Possession or Custody of an Investment Advisor',
    'ADV-H-C': ' | |Application for Continuing Hardship Exemption',
    'ADV-H-T': ' | |Application for Temporary Hardship Exemption',
    'ADV-NR': ' | |Appointment of Agent for Service of Process by Non-Resident General Partner and Non-Resident managing agent of an Investment Advisor',
    'ADVW': ' | |Notice of withdrawal from Registration as Investment Advisor',
    'AFDB': 'a| |African Development Bank',
    'ANNLRPT': 'a| |Periodic Development Bank filing, submitted annually',
    'APP NTC': ' | |40-APP Notice',
    'APP ORDR': ' | |40-APP Order',
    'APP WD': 'a| |Withdrawal of an Application for exemption [Section 12(g)] or from filing certain reports [Section 13(a)]',
    'ARS': ' |3|Annual Report to Security Holders',
    'AW': ' |3|Amendment Withdrawal Request',
    'AW WD': ' | |Amendment Withdrawal (Withdrawal Duplicate) Requests',
    'BDCO': ' | |Cancellation of Registered Brokers or Dealers by Commission Order',
    'BW-2': ' |2|Periodic World Bank filing, submitted quarterly',
    'BW-3': ' |2|Transactional World Bank filing',
    'CA-1': ' | |Registration as a Clearing Agency',
    'C': 'a| |Offering Statement',
    'C/A-W': 'a | |Offering Statement Withdrawal',
    'C-W': 'a| |Offering Statement Withdrawal',
    'C-U': 'a| |Progress Update',
    'C-U-W': 'a| |Progress Update Withdrawal',
    'C-AR': 'a| |Annual Report',
    'C-AR-W': 'a| |Annual Report Withdrawal',
    'C-AR/A-W': 'a| |Annual Report Withdrawal',
    'C-TR': 'a| |Termination of Reporting',
    'C-TR-W': 'a| |Termination of Reporting Withdrawal',
    'CB': 'a| |Tender Offer/Rights Offering Notification Form',
    'CERTAMX': ' | |Certification by the American Stock Exchange approving securities for listing',
    'CERTARCA': 'a||Certification by the New York Stock Exchange Archipelago approving securities for listing',
    'CERTBSE': ' | |Certification by the Boston Stock Exchange approving securities for listing',
    'CERTCBO': ' | |Certification by the Chicago Board of Options approving securities for listing',
    'CERTCIN': ' | |Certification by the Cincinnati Stock Exchange approving securities for listing',
    'CERTCSE': ' | |Certification by the Central Stock Exchange, formerly Midwest Stock Exchange, to approve listing of securities',
    'CERTISE': ' | |Certification by the International Stock Exchange approving securities for listing',
    'CERTNAS': ' | |Certification by the Nasdaq Stock Market approving securities for listing',
    'CERTNYS': ' | |Certification by the New York Stock Exchange approving securities for listing',
    'CERTPAC': ' | |Certification by the Pacific Coast Stock Exchange approving securities for listing',
    'CERTPBS': ' | |Certification by the Philadelphia Stock Exchange approving securities for listing',
    'CORRESP': ' |4|Correspondence',
    'CT ORDER': ' ||Confidential treatment order',
    'D': 'a||Notice of Exempt Offering of Securities',
    'DEF13E3': 'a| |Schedule filed as definitive materials.',
    'DEF 14A': ' |2|Other definitive proxy statements',
    'DEF 14C': ' |2|Other definitive information statements',
    'DEFA14A': ' |2|Additional definitive proxy soliciting materials and Rule 14(a)(12) material',
    'DEFA14C': ' |2|Additional information statement materials, definitive',
    'DEFC14A': ' |2|Definitive proxy statement, contested solicitations',
    'DEFC14C': ' |2|Definitive information statement, contested solicitations',
    'DEFM14A': ' |2|Definitive proxy statement relating to merger or acquisition',
    'DEFM14C': ' |2|Definitive information statement relating to merger or acquisition',
    'DEFN14A': ' |2|Definitive proxy statement filed by non-management',
    'DEF-OC': 'a| |Definitive offering circular (Regulation A)',
    'DEFR14A': ' |2|Revised definitive proxy soliciting materials',
    'DEFR14C': ' |2|Revised information statement materials, definitive',
    'DEFS14A': ' |2|Definitive proxy statement for special meeting',
    'DEFS14C': ' |2|Definitive information statement for special meeting',
    'DEL AM': ' |3|Delaying amendment',
    'DFAN14A': ' |2|Additional definitive proxy soliciting materials filed by non-management and Rule 14(a)(12) material',
    'DFRN14A': ' |2|Revised definitive proxy statement filed by non-management',
    'DRS': 'a| |Draft Registration Statement',
    'DRSLTR': 'a| |Correspondence Related to Draft Registration Statement',
    'DSTRBRPT': ' | |Distribution of primary obligations Development Bank report',
    'EBRD': 'a| |European Bank for Reconstruction and Development',
    'EFFECT': 'a|2|Notice of Effectiveness',
    'QUALIF': 'a|2|Notice of Qualification [Regulation A]',
    'F-10': 'a| |Registration Statement for Securities of certain Canadian Issuers.',
    'F-10EF': ' | |Registration Statement for Securities of certain Canadian Issuers, immediately effective.',
    'F-10MEF': ' |1|Registration statement to add securities to prior Form F-10 registration [Rule 462(b)]',
    'F-10POS': ' | |Post-effective amendment to a F-10EF registration',
    'F-1': 'a|1|Registration statement for certain foreign private issuers',
    'F-1MEF': ' |1|Registration statement to add securities to prior Form F-1 registration [Rule 462(b)]',
    'F-2': ' |1|Registration statement for certain foreign private issuers',
    'F-2D': ' |1|Registration of securities, dividend or interest re-investment plans',
    'F-2DPOS': ' |1|Registration of securities, dividend or interest re-investment plans, post-effective amendments',
    'F-2MEF': ' |1|Registration statement to add securities to Form F-2 registration [Rule 462(b)]',
    'F-3': ' |1|Registration statement by foreign private issuers',
    'F-3ASR': 'a| |Automatic shelf registration statement of securities of well-known seasoned issuers',
    'F-3D': ' |1|Registration of securities pursuant to dividend or interest reinvestment plans',
    'F-3DPOS': ' |1|Registration of securities pursuant to dividend or interest reinvestment plans, post-effective amendments',
    'F-3MEF': ' |1|Registration statement to add securities to prior Form F-3 registration [Rule 462(b)]',
    'F-4': 'a|1|Registration of securities, foreign private issuers, business combinations',
    'F-4EF': ' | |Registration of securities, foreign private issuers, business combinations, immediately effective.',
    'F-4MEF': ' |1|Registration statement to add securities to prior Form F-4 registration [Rule 462(b)]',
    'F-4 POS': ' | |Registration of securities, foreign private issuers, business combinations, post effective',
    'F-6EF': ' | |Registration of American Depository Receipt shares, immediately effective',
    'F-6 POS': ' |1|Post-effective amendments for immediately effective filing',
    'F-6': ' | |Registration of American Depository Receipt shares, not immediately effective',
    'F-7 POS': ' | |Post-effective amendment to a F-7 registration',
    'F-7': ' | |Registration statement for securities of certain Canadian issuers offered for cash upon the exercise of rights granted to existing security holders',
    'F-80': 'a| |Registration of securities of certain Canadian Issuers in exchange offers or a business combination.',
    'F-80POS': ' | |Post-effective amendment to a F-80 registration',
    'F-8': 'a| |Registration statement for securities of certain Canadian issuers to be issued in exchange offers or a business combination',
    'F-8 POS': ' | |Registration statement for securities of certain Canadian issuers, post effective',
    'F-9': 'a| |Registration of securities of certain investment grade debt of preferred securities of certain Canadian issuers.',
    'F-9EF': ' | |Registration of securities of certain investment grade debt of preferred securities of certain Canadian issuers, immediately effective.',
    'F-9MEF': ' |1|Registration statement to add securities to prior Form F-9 registration [Rule 462(b)]',
    'F-9 POS': ' | |Post-effective amendment to a F-9EF registration',
    'F-N': ' | |Designates a U.S. agent for service of process by foreign banks and foreign insurance companies',
    'FOCUSN': 'a| |Non-public annual audit reports filed by brokers or dealers',
    'FWP': 'a| |Filing under Securities Act Rules 163/433 of free writing prospectuses',
    'F-X': 'a| |Appointment of Agent for Service of Process and Undertaking',
    'G-405': 'a| |Report on Financial Operations – aka FOGS Report',
    'G-FIN': 'a| |notification by financial institutions of status',
    'G-FINW': ' | |Notice of withdrawal from government securities broker or dealer by financial institutions',
    'HISTORY': ' | |Captures Historical File Numbers assigned to issuers or applicants prior to the recording of information on the Automated Workload Filings System',
    'IADB': 'a| |Inter-American Development Bank',
    'IBRD': 'a| |International Bank for Reconstruction and Development',
    'ID-NEWCIK': ' | |New Form ID Submission',
    'IFC': 'a| |Periodic Reports filed by the International Finance Corporation',
    'MSD': 'a| |Registration of Municipal Securities Dealer',
    'MSDCO': ' | |Cancellation of Registered Municipal Securities Dealers by Commission Order',
    'MSDW': ' | |Notice of Withdrawal from Registration as a Municipal Securities Dealer [Rule 15Bc3-1]',
    'N-14 8C': 'a|1|Registration statement for closed-end investment company (business combinations)',
    'N-14': 'a|1|Registration statement for open-end investment company (business combinations)',
    'N14AE24': 'a| |Registration statements of open end investment companies (business combinations)',
    'N-14AE': 'a|1|Registration statement for open-end investment company (business combinations) [Rule 488]',
    'N14EL24': 'a| |Registration statements of open end investment companies (business combinations)',
    'N-14MEF': ' |1|Registration of additional securities for a Form N-14 offering [Rule 462(b)]',
    'N-18F1': 'a|2|Notification of election [Rule 18f-1]',
    'N-1': 'a|1|Registration for open-end management investment companies',
    'N-1A': 'a|1|Registration statement for open-end management investment companies',
    'N-1A EL': 'a| |Registration statements of open end management investment companies',
    'N-23C-1': 'a|2|Reports by closed-end investment companies of purchase of their own securities',
    'N-23C-2': 'a|2|Notice by closed-end investment companies of intent to purchase their own securities',
    'N-23C3A': 'a|2|Notification of periodic repurchase offer [Rule 23c-3(b) only]',
    'N-23C3B': 'a|2|Notification of periodic repurchase offer [Rule 23c-3(c) only]',
    'N-23C3C': 'a|2|Notification of periodic repurchase offer [Rule 23c-3(b) and (c)]',
    'N-27D-1': 'a|2|Accounting for segregated trust accounts',
    'N-2': 'a|1|Registration statement for closed-end investment companies',
    'N-2MEF': ' |1|Registration of additional securities for a Form N-2 offering [Rule 462(b)]',
    'N-30B-2': ' |3|Periodic and interim reports mailed to shareholders',
    'N-30D': 'a|3|Annual and semi-annual reports mailed to shareholders [Rule 30d-1]',
    'N-3': 'a|1|Registration statement for separate accounts (management investment companies)',
    'N-3 EL': 'a| |Registration statements for separate accounts (management investment companies)',
    'N-4': 'a|1|Registration statement for separate accounts (unit investment trusts)',
    'N-4 EL': 'a| |Registration statements for separate accounts (unit investment trusts)',
    'N-54A': 'a|2|Notification of election by business development companies',
    'N-54C': 'a|2|Notification of withdrawal by business development companies',
    'N-5': 'a|1|Registration statement for small business investment companies',
    'N-6': 'a|1|Registration statement for separate accounts (unit investment trusts)',
    'N-6C9': 'a| |Exemptions for Foreign Banks',
    'N-6F': 'a|2|Notice of intent by business development companies to be subject to Sections 55 through 65',
    'N-8A': 'a|2|Notification of registration [Section 8(a)]',
    'N-8B-2': 'a|2|Registration statement for unit investment trusts',
    'N-8B-3': 'a|2|Registration statement for periodic payment Plans',
    'N-8B-4': 'a|2|Registration statement for face-amount certificate companies',
    'N-8F': 'a| |Application for Deregistration',
    'N-8F NTC': ' | |N-8F Notice',
    'N-8F ORDR': ' | |N-8F Order',
    'N-CSR': 'a| |Certified Shareholder Report',
    'N-CSRS': 'a| |Certified Shareholder Report, Semi-Annual',
    'N-MFP': 'a||Monthly Schedule Of Portfolio Holdings Of Money Market Funds',
    'NO ACT': ' | |No Action Letter',
    'N-PX': 'a| |Annual Report of proxy voting record of management investment companies',
    'N-Q': 'a| |Quarterly Schedule of portfolio holdings of management investment companies',
    'NSAR-A': 'a|3|Semi-annual report for management companies',
    'NSAR-AT': 'a|3|Transitional semi-annual report',
    'NSAR-B': 'a|3|Annual report for management companies',
    'NSAR-BT': 'a|3|Transitional annual report for management companies',
    'NSAR-U': 'a|3|Annual report for unit investment trusts',
    'NT 10-D': 'a| |Notification of inability to timely file Form 10-D',
    'NT 10-K': 'a|3|Notification of inability to timely file Form 10-K 405, 10-K, 10-KSB 405, 10-KSB, 10-KT, or 10-KT405',
    'NT 10-Q': 'a|3|Notification of inability to timely file Form 10-Q or 10-QSB',
    'NT 11-K': 'a|3|Notification of inability to timely file Form 11-K',
    'NT 15D2': 'a|3|Notification of inability to timely file special report [Section 15d-2]',
    'NT 20-F': 'a|3|Notification of inability to timely file Form 20-F',
    'NTFNCSR': 'a| |Notification of late filings of form N-CSR',
    'NTFNSAR': ' | |Notices of Late Filings of Form N-SAR',
    'NTN 10-D': 'a| |Notices of Late Filings of Form 10-D',
    'NTN 10D': 'a| |Notification of late filings of form 10-D',
    'NTN 10K': ' | |Notices of Late Filings of Form 10-K or 10-KSB',
    'NTN 10Q': ' | |Notices of Late Filings of Form 10-Q or 10-QSB',
    'NTN 11K': ' | |Notices of Late Filings of Form 11-K',
    'NTN15D2': ' | |Notices of Late Filings of Special Financial Reports',
    'NTN 20F': ' | |Notices of Late Filings of Form 20-F',
    'NT-NCSR': 'a| |Notice under Exchange Act Rule 12b-25 of inability to timely file Form N-CSR (annual or semi-annual report)',
    'NT N-MFP': ' | |Notification of late filings of form N-MFP',
    'NT-NSAR': 'a|3|Notification of inability to timely file Form N-SAR',
    'OC': 'a| |Offering Circular [Regulation A]',
    'OIP NTC': ' | |40-OIP Notice',
    'OIP ORDR': ' | |40-OIP Order',
    'POS462B': ' |3|Post-effective amendment to registration statement [Rule 462(b)]',
    'POS462C': ' |3|Post-effective amendment to registration statement [Rule 462(c)]',
    'POS 8C': ' |3|Post-effective amendments filed by certain investment companies [Section 8(c)]',
    'POS AM': ' |1|Post-Effective amendments for registration statement',
    'POS AMC': ' |3|Pre-effective amendments for application or declaration',
    'POS AMI': ' |3|Amendments to 40 Act only filings',
    'POSASR': 'a| |Post-effective Amendment to an automatic shelf registration statement',
    'POS EX': ' |3|Post-effective amendment adding exhibits to registration statement [Rule 462(d)]',
    'PRE13E3': 'a| |Initial statement - preliminary form.',
    'PRE 14A': ' |2|Other preliminary proxy statements',
    'PRE 14C': ' |2|Other preliminary information statements',
    'PREA14A': ' | |Additional Preliminary Proxy Solicitation Material',
    'PREA14C': ' | |Additional Preliminary Proxy Information Statements',
    'PREC14A': ' |2|Preliminary proxy statements, contested solicitations',
    'PREC14C': ' |2|Preliminary information statements, contested solicitations',
    'PREM14A': ' |2|Preliminary proxy statements relating to merger or acquisition',
    'PREM14C': ' |2|Preliminary information statements relating to merger or acquisition',
    'PREN14A': ' |2|Non-management preliminary proxy statements',
    'PRER14A': ' | |Preliminary Proxy Soliciting materials',
    'PRER14C': ' |2|Information statements',
    'PRES14A': ' |2|Preliminary proxy statements, special meeting',
    'PRES14C': ' |2|Preliminary information statements, special meeting',
    'PRRN14A': ' |2|Non-management revised preliminary proxy soliciting materials, contested and otherwise',
    'PWR-ATT': 'a| |Power of Attorney',
    'PX14A6G': ' |2|Notice of exempt solicitation submitted by non-management',
    'PX14A6N': ' |2|Notice of exempt solicitation submitted by non-management',
    'QRTLYRPT': ' | |Periodic Development Bank filing, submitted quarterly',
    'REGDEX': 'a| |Notice of Sale of Securities [Regulation D and Section 4(6) of the Securities Act of 1933]',
    'REG-NR': 'a| |Initial undertaking of records for non-resident brokers, dealers and investment advisers',
    'REVOKED': ' | |Commission order revoking Exchange Act registration [Section 12(j)]',
    'RW': ' |3|Registration Withdrawal Request',
    'RW WD': ' | |Withdrawal of Registration Withdrawal Request',
    'S-11': 'a|1|Registration of securities issued by real estate companies',
    'S-11MEF': ' |1|Registration adding securities to prior Form S-11 registration [Rule 462(b)]',
    'S-1': 'a|1|General form for registration of securities under the Securities Act of 1933',
    'S-1MEF': ' |1|Registration adding securities to prior Form S-1 registration [Rule 462(b)]',
    'S-20': 'a|1|For standardized options',
    'S-2': 'a|1|Registration of securities',
    'S-2MEF': ' |1|Registration adding securities to prior Form S-2 registration [Rule 462(b)]',
    'S-3': 'a|1|Registration statement under Securities Act of 1933',
    'S-3ASR': 'a| |Automatic shelf registration statement of securities of well-known seasoned issuers',
    'S-3DPOS': ' |1|Post-effective amendments, registration of securities, dividend or interest reinvestment plans, immediately effective',
    'S-3D': ' | |Registration of securities, dividend or interest reinvestment plans, immediately effective',
    'S-3MEF': ' |1|Registration adding securities to prior Form S-3 registration [Rule 462(b)]',
    'S-4': 'a|1|Registration of securities, business combinations',
    'S-4EF': 'a|1|Securities issued, formation of bank or savings and loan holding company [General Instruction G]',
    'S-4MEF': ' |1|Registration adding securities to prior Form S-4 registration [Rule 462(b)]',
    'S-4 POS': 'a|1|Securities issued, formation of bank or savings and loan holding company [General Instruction G], post-effective amendments',
    'S-6': 'a|1|Registration statement for unit investment trusts',
    'S-6EL24': 'a| |Registration statements of unit investment trusts',
    'S-8': ' |1|Securities to be offered to employees in employee benefit plans',
    'S-8 POS': ' |1|Securities to be offered to employees in employee benefit plans, post-effective amendments',
    'SB-1': 'a|1|Optional form for registration of securities to be sold to the public by small business issuers',
    'SB-1MEF': ' |1|Registration adding securities to prior Form SB-1 registration [Rule 462(b)]',
    'SB-2': 'a|1|Optional form for registration of securities to be sold to the public by small business issuers',
    'SB-2MEF': ' |1|Registration adding securities to prior Form SB-2 registration [Rule 462(b)]',
    'S-B': 'a| |Registration statement for securities of Foreign Governments and Subdivisions',
    'S-BMEF': ' | |A new registration statement filed under Rule 462(b) to add securities to a prior related effective registration statement filed on Form S-B',
    'SC 13D': 'a|2|General statement of acquisition of beneficial ownership',
    'SC 13E1': 'a|2|Statement of issuer required by Rule 13e-1',
    'SC 13E3': 'a|2|Going private transaction by certain issuers',
    'SC 13E4': 'a|2|Issuer tender offer statement, amendments',
    'SC13E4F': ' | |Canadian Foreign Private Issuer tender offer statement.',
    'SC 13G': 'a|2|Statement of acquisition of beneficial ownership by individuals',
    'SC 14D1': 'a|2|Tender offer statement, amendments',
    'SC14D1F': 'a| |Tender Offer Statement [Rule 14d-1(b)]',
    'SC 14D9': 'a|2|Solicitation, recommendation statements',
    'SC14D9': 'a|2|Solicitation, recommendation statements',
    'SC14D9C': ' |2|Written communication relating to third party tender offer',
    'SC14D9F': 'a| |Solicitation/Recommendation Statements',
    'SC 14F1': 'a|2|Statement regarding change in majority of directors [Rule 14f-1]',
    'SC 14N': 'a| |Information filed by certain nominating shareholders (pursuant to Section 240.14n-1)',
    'SC 14N-S': 'a| |Solicitation in connection with the formation or attempted formation of a Rule 14a-11 nominating shareholder group or solicitation in connection with a Rule 14a-11 nomination',
    'SC TO-C': ' |2|Written communication relating to an issuer or third party',
    'SC TO-I': 'a|2|Tender offer statement by Issuer',
    'SC TO-T': 'a|2|Tender offer statement by Third Party',
    'SDR': 'a| |Security-Based Swap Data Repository Registration',
    'SDR-A': 'a| |[Annual Amend] Security-Based Swap Data Repository Registration',
    'SDR-W': 'a| |Security-Based Swap Data Repository Withdrawal',
    'SE': ' | |Exhibits',
    'SH-ER': 'a||Weekly Form SH Entries Report Filed by Institutional Investment Managers',
    'SH-NT': 'a||Weekly Form SH Notice Report Filed by Institutional Investment Managers',
    'SL': ' | |Sales Literature',
    'SP 15D2': 'a|3|Special Financial Report [Rule 15d-2]',
    'Stop Order': ' | |Commission stop order for deficient Securities Act registration statement [Section 8]',
    'SUPPL': ' | |Voluntary Supplemental Material by Foreign Issuers [Section 11(a)]',
    'T-3': 'a||Application for qualification of trust indentures',
    'TA-1': 'a| |Registration of Transfer Agent',
    'TA-2': 'a| |Annual disclosure filing made by all bank and non-bank Transfer Agents',
    'TACO': '||Cancellation or Registered Transfer Agents by Commission Order',
    'TA-W': ' | |Transfer Agent Registration Withdrawal',
    'TH': ' | |Notification of reliance on temporary hardship exemption',
    'TTW': '||\'Test The Waters\' submission [Regulation A]',
    'U-12-IA': 'a|2|Statement by holding company employee [Section 12(i)]',
    'U-12-IB': 'a|2|Three-year statement by holding company employee [Section 12(i)]',
    'U-13-1': 'a|3|Application for approval of mutual service company [Rule 88]',
    'U-13-60': 'a|3|Annual report for mutual and subsidiary service companies [Rule 94]',
    'U-13E-1': 'a|2|Report by affiliate or independent service companies [Rule 95]',
    'U-1': 'a|3|Application or declaration under the act',
    'U-33-S': 'a|3|Annual report Concerning Foreign Utility Companies [Section 33(e)]',
    'U-3A-2': 'a|3|Statement by holding company claiming exemption [Rule 2]',
    'U-3A3-1': 'a|3|Twelve-month statement by bank claiming exemption [Rule 3]',
    'U-57': 'a|2|Notification of Foreign Utility Company Status [Section 33(a)(2)]',
    'U5A': 'a|3|Notification of registration [Section 5(a)]',
    'U5B': 'a|3|Registration statement filed under [Section 5]',
    'U5S': 'a|3|Annual report for holding companies [Section 5]',
    'U-6B-2': 'a|3|Notification of security issue, renewal or guaranty [Rule 20(d)]',
    'U-7D': 'a|2|Certificate, lease of utility facility [Rule 7(d)]',
    'U-9C-3': 'a|3|Quarterly report, energy and gas companies [Rule 58]',
    'UNDER': 'a|3|Undertaking to file reports, [Item 4 Form S-6]',
    'UPLOAD': ' | |SEC-generated letter',
    'U-R-1': 'a|3|Declaration as to solicitations [Rule 62]',
    'WDL-REQ': '||Withdrawal Request for Materials Filed [Regulation A only]',
    'X-17A-5': 'a| |FOCUS Report',
    'IRANNOTICE': ' | |Notice of disclosure filed pursuant to Section 219 of the Iran Threat Reduction and Syria Human Rights Act of 2012 (Exchange Act Section 13(r)).',
    'N-CEN': 'a| |Annual Report for Registered Investment Companies',
    'NT-NCEN': 'a| |Notice under Exchange Act Rule 12b-25 of inability to timely file Form N-CEN',
    'NT N-CEN': '| |EDGAR generated form type for late filing of Annual Report for Registered Investment Companies',
    'NTFNCEN': '| |EDGAR generated form type for late filing of notice under Exchange Act Rule 12b-25 of inability to timely file Form N-CEN',
    'NPORT-P': 'a| |Monthly Portfolio Investments Report on Form N-PORT (Public)',
    'NPORT-NP': 'a| |NPORT-NP: Monthly Portfolio Investments Report on Form N-PORT (Non-Public)',
    'NPORT-EX': 'a| |Portfolio Holdings Exhibit to Form N-PORT',
    'NT NPORT-P': '| |EDGAR generated form type for a late filing of a Monthly Portfolio Investments Report on Form N-PORT (Public)',
    'NT NPORT-N': '| |EDGAR generated form type for a late filing of a Monthly Portfolio Investments Report on Form N-PORT (Non-Public)',
    'NT NPORT-EX': '| |EDGAR generated form type for a late filing of a Portfolio holdings exhibit',
    '1-U': 'a||Current Report Pursuant to Regulation A',
    'SEC STAFF ACTION': '||SEC Staff Action',
    'SEC STAFF LETTER': '||SEC Staff Letter',
    'SEC ACTION': '||SEC Action',
    'MA': '||Municipal Advisor Registration for Business Entities',
    'MA-I': '||Application for Municipal Advisor Registration for Natural Persons',
    'MA-W': '||Notice of Withdrawal from Registration as a Municipal Advisor',
    'MA-A': '||Annual Update of Munipal Advisor Registration for Business Entities',
    'STOP ORDER': '||Stop Order',
    'ATS-N': '||Initial Form ATS-N (Rule 304(a)(1)(i))',
    'ATS-N/MA CP': 'a||Cover Page of an Material Amendment to Form ATS-N (Rule 304(b)(2)(iii)(A))',
    'ATS-N/MA': 'a||Material Amendment to Form ATS-N (Rule 304(a)(2)(i)(A))',
    'ATS-N/UA': 'a||Updating Amendment to Form ATS-N (Rule 304(a)(2)(i) (B))',
    'ATS-N/CA': 'a||Correcting Amendment to Form ATS-N (Rule 304(a)(2)(i)(C))',
    'ATS-N/OFA': 'a||Order Display and Fair Access Amendment to Form ATS-N (Rule 304(a)(2)(i)(D))',
    'ATS-N-C': '||Notice of Cessation of Operations of NMS Stock ATS (Rule 304(a)(3))',
    'ATS-N-W': '||Withdrawal of Form ATS-N Filing (Form ATS-N Instruction No. 9)',
    'ATS-N ORDR INEFF': '||Order of Ineffective Initial Form ATS-N (Rule 304(a)(1)(iii)(B))',
    'ATS-N/A ORDR INEFF': '||Order of Ineffective Form ATS-N Amendment (Rule 304(a)(2)(ii))',
    'ATS-N ORDR SUSP': '||Order of Suspension of the Exemption from the Definition of Exchange (Rule 304(a)(4)(i))',
    'ATS-N ORDR REVK': '||Order of Revocation of the Exemption from the Definition of Exchange (Rule 304(a)(4)(i))',
    'ATS-N ORDR LTD OPN': '||Order of Limitation of the Exemption from the Definition of Exchange (Rule 304(a)(4)(i))'
}

  constructor(
    private tickerSync: TickerSyncService,
    private edgarSearch: EdgarSearchService,
    private edgarPreview: EdgarPreviewService
  ) { }

  ngOnInit() {
    this.tickerSync.currentTicker.subscribe(ticker => {
      this.company = ticker;
      if (ticker.length > 0) {
        let _cik: any = ticker.match(/\d+/g);
        let cik: any = _cik[0];
        this.edgarSearch.fetchFillings(cik).subscribe(data => this.filterLinks(data as FillingsStucture));
      }
    })
  }

  filterLinks(data: FillingsStucture) {
    this.filingsArray = [];
    console.log(data);
    Object.values(data).forEach((el: FillingsStucture) => {
      this.filingsData = el;
      for (let i in el.filings.recent.form) {
        let _an = el.filings.recent.accessionNumber[i];
        let an = _an.replace(/-/g, '');
        let formDesc = this.findFormDesc(el.filings.recent.form[i]);
        console.log(formDesc);
        let url = `https://www.sec.gov/Archives/edgar/data/${el.cik}/${an}/${el.filings.recent.primaryDocument[i]}`;
        this.filingsArray.push({i: [el.filings.recent.form[i], formDesc, el.filings.recent.filingDate[i], url]});
      }
    })
    // console.log(this.submissionForms);
    // console.log(this.filingsArray);
  }

  findFormDesc(form: string) {
    let desc: string = '';
    Object.entries(this.submissionForms).forEach(([k, v]) => {
      if (k == form) {
        desc = v;
      }
    })
    return desc;
  }

}